[package]
name = "rust_runner_example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rust_runner = { path = "../runner" }

serde = { workspace = true, features = ["derive"] }
serde_yaml.workspace = true
tokio = { workspace = true, features = ["full"] }
